### ISSUE TITLE
Dasmoto's Arts & Crafts Review

### ISSUE THREAD

**Issue by franfranfranfran** [SecretPunk/prj-rev-bwfs-dasmoto#1]
### Criteria 1: HTML and CSS Linking  
* _Score Level:_ 4
* _Comment(s):_ Great job linking up the CSS file to the HTML!
 
### Criteria 2: Implementation of Design Specification and Content
* _Score Level:_ 4
* _Comment(s):_ Great work matching up the styling of your page to that of the given design spec. It looks like everything matches up perfectly!
 
### Criteria 3: HTML Elements and Content
* _Score Level:_ 4
* _Comment(s):_ Excellent use of various HTML elements to help group together your content on the page. Nice job keeping everything consistent throughout each section and with going above and beyond using the section tags. 
 
### Criteria 4: CSS Selectors and Syntax
* _Score Level:_ 4
* _Comment(s):_ Overall, nice job keeping the CSS clean and simple by making use of classes and ids throughout. Good idea to apply common styling, like the font-family, to many elements at once. One thing I noticed is that you could likely get rid of either the ids or the classes for each section. Right now, the id names are not being used and they match the class names exactly. In general, try to avoid adding in extra, unused code wherever possible. 
 
### Overall Score: 16/16
Awesome work on this project! The page looks great and you've done an excellent job keeping both the project folder and the code itself neat organized and readable throughout. Nice use of relative file paths to link to both the CSS file and the necessary images as well.
From here, you’re in a great place to spruce up the page beyond what the spec shows. You could try any number of things. One possibility is to put the item text in each section up next to the image. How might we accomplish this? Check [here](https://developer.mozilla.org/en-US/docs/Web/CSS/float?v=example) for more info.

Have fun and keep up the good work!

**Comment by ghost** [comment]
Thank you for this useful feedback! I understand your point about redundant section ids.
